[package]
name = "fawkes-crypto"
version = "0.1.0"
authors = ["Igor Gulamov <igor.gulamov@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "lib", "staticlib"]

[dependencies]
blake2-rfc = {git = "https://github.com/gtank/blake2-rfc", rev = "7a5b5fc99ae483a0043db7547fb79a6fa44b88a9"}
rand = "0.4"
byteorder = "1"
num = "0.2.1"
maplit = "1.0.2"
linked-list = "0.0.3"

[dependencies.bellman]
version = "0.3.1"
package = "bellman_ce"

[dependencies.ff]
version = "0.7"
features = ["derive"]
package = "ff_ce"


[dependencies.pairing]
version = "0.18.0"
package = "pairing_ce"

[dev-dependencies.sapling_crypto]
version = "0.1.2"
package = "sapling-crypto_ce" 