[package]
name = "fawkes-crypto"
version = "3.0.0"
authors = ["Igor Gulamov <igor.gulamov@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]


[dependencies]

ff-uint = {path="../ff-uint"}
linked-list = {version="0.0.3", optional=true}

[features]
default=["plonk"]
r1cs=["linked-list"]
plonk=[]