[package]
name = "fawkes-crypto"
version = "3.0.0"
authors = ["Igor Gulamov <igor.gulamov@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]


[dependencies]

ff-uint = {path="../ff-uint"}
linked-list = {version="0.0.3", optional=true}
typenum = "1.12.0"
rand = "0.7.3"
byteorder = "1"
serde = { version = "1.0", features = ["derive"] }
borsh = "0.7"
fawkes-crypto_derive = {version="3.0.0", path = "../fawkes-crypto_derive"}
impl-trait-for-tuples = "0.1.3"
getrandom = "0.2"

[dependencies.blake2_rfc]
version = "0.0.1"
package = "blake2-rfc_bellman_edition"


[dependencies.bellman]
version = "0.3.1"
package = "fawkes-crypto-bellman_ce"
default_features = false
optional = true

[dependencies.bellman_rand]
version = "0.4"
package = "rand"
optional = true


[features]
default=["backend_bellman_groth16", "r1cs"]
r1cs=["linked-list"]
plonk=[]
backend_bellman_groth16=["bellman", "bellman_rand"]